version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: michael6cohen/async-task-processor:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure